//
//  MovieGenre.swift
//  MovieHunter
//
//  Created by Yang Xu on 2023/3/17.
//

import Foundation
import SwiftUI
import TMDb

// Code generated by OpenAI
enum Genres: Int, CaseIterable, Hashable {
    case action = 28
    case adventure = 12
    case animation = 16
    case comedy = 35
    case crime = 80
    case documentary = 99
    case drama = 18
    case family = 10751
    case fantasy = 14
    case history = 36
    case horror = 27
    case music = 10402
    case mystery = 9648
    case romance = 10749
    case scienceFiction = 878
    case tvMovie = 10770
    case thriller = 53
    case war = 10752
    case western = 37

    init?(id: Int) {
        switch id {
        case 28: self = .action
        case 12: self = .adventure
        case 16: self = .animation
        case 35: self = .comedy
        case 80: self = .crime
        case 99: self = .documentary
        case 18: self = .drama
        case 10751: self = .family
        case 14: self = .fantasy
        case 36: self = .history
        case 27: self = .horror
        case 10402: self = .music
        case 9648: self = .mystery
        case 10749: self = .romance
        case 878: self = .scienceFiction
        case 10770: self = .tvMovie
        case 53: self = .thriller
        case 10752: self = .war
        case 37: self = .western
        default: return nil
        }
    }
}

extension Genres: Identifiable {
    var id: Int {
        rawValue
    }

    var localizedString: LocalizedStringKey {
        switch self {
        case .action:
            return "Genre_action"
        case .adventure:
            return "Genre_adventure"
        case .animation:
            return "Genre_animation"
        case .comedy:
            return "Genre_comedy"
        case .crime:
            return "Genre_crime"
        case .documentary:
            return "Genre_documentary"
        case .drama:
            return "Genre_drama"
        case .family:
            return "Genre_family"
        case .fantasy:
            return "Genre_fantasy"
        case .history:
            return "Genre_history"
        case .horror:
            return "Genre_horror"
        case .music:
            return "Genre_music"
        case .mystery:
            return "Genre_mystery"
        case .romance:
            return "Genre_romance"
        case .scienceFiction:
            return "Genre_scienceFiction"
        case .tvMovie:
            return "Genre_tvMovie"
        case .thriller:
            return "Genre_thriller"
        case .war:
            return "Genre_war"
        case .western:
            return "Genre_western"
        }
    }
}
